### ISSUE TITLE
增加pretty format支持？

### ISSUE THREAD

**Issue by hengyunabc** [smallnest/fastjson-jaxrs-json-provider#1]
比如用户在请求参数里有 ?pretty=true ，则输出格式化好的JSON数据。

当然，简单地可以全局地实现配置FastJSON都输出格式化好的，但如果想从请求参数里来判断，需要用Filter来处理？

**Comment by smallnest** [comment]
因为Provider无法直接得到请求的url,所以只能通过配置Config的方式设置pretty format.
fastJsonConfig.serializerFeatures = new SerializerFeature[]{SerializerFeature.PrettyFormat}

**Comment by hengyunabc** [comment]
这里下面有个答案好像可以拿到请求参数的？

http://stackoverflow.com/questions/10532217/jax-rs-json-pretty-output

**Comment by smallnest** [comment]
implemented. 如果请求的url中包含?pretty=true则输出pretty格式。
版本 0.3.0

**Comment by hengyunabc** [comment]
感觉pretty参数判断那里这样子判断好点：

``` java
        // check pretty parameter
        if (uriInfo != null) {
            List<String> prettyList = uriInfo.getQueryParameters().get("pretty");
            if (prettyList != null && !prettyList.isEmpty() && !prettyList.get(0).equalsIgnoreCase("false")) {
```

**Comment by smallnest** [comment]
pretty=true是没必要的。你发送的url格式应该类似http://httpbin.org/get?pretty&a=b这样的方式，不要发送冗余的数据

**Comment by hengyunabc** [comment]
你说的有道理。只是觉得发送一个 pretty=false ，也会输出格式化好的数据，有一点奇怪。
